### PR TITLE
Build improvements for Ubuntu 18.04.3

### PR DESCRIPTION
**Pull request by bigfatbrowncat**
Due to some updates in the Perl interpreter and some minor changes in automake/autoconf the current version couldn't build on Ubuntu 18.04 (LTS) out of the box

Here is the version that has proven to be built (and run on RG280V) successfully

Please consider merging it upstream. Thank you!

### CODE REVIEW

**Comment by Ninoh-FOX** [comment]
how can I put this in another brash?

**Comment by bigfatbrowncat** [comment]
Create a branch and let me know. I will make a PR to it.

**Comment by Ninoh-FOX** [comment]
https://github.com/Ninoh-FOX/toolchain/tree/Ubuntu

**Comment by Ninoh-FOX** [comment]
please, changed to the ubuntu branch, thanks

**Pull request closed without merging**
